# Generated by Django 2.0 on 2019-05-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20190503_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petadmin',
            name='pet_ptr',
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(blank=True, choices=[('강아지', '강아지'), ('고양이', '고양이'), ('기타', '기타')], max_length=50),
        ),
        migrations.DeleteModel(
            name='PetAdmin',
        ),
    ]
