# Generated by Django 2.0 on 2019-05-06 00:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_auto_20190506_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=''),
        ),
    ]
