# Generated by Django 2.0 on 2019-05-06 00:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20190506_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='allergies_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', encoder=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='diseases_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', encoder=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', encoder=''),
        ),
    ]
